### PR TITLE
fix(tap): Fix incremental sync

### PR DESCRIPTION
**Pull request by rvantunes**
## Context

* Incremental sync was not working as expected by syncing the last file that was already synced in a previous execution. See [this test](https://github.com/rvantunes/tap-universal-file/blob/611d69157727392958d9e447daf55343b2db562c/tests/test_core.py#L243-L265) to understand the expected behavior.
   * If I run the sync command twice with no changes on input files it should not sync any data, but the current implementation is syncing again the data that were synced in the first execution, duplicating data
* start_date filters by before or equal to unify the behavior from start_date and state, simplifying the code.
* added a new row to the file: `tests/data/new_hardware.csv` to differ the number of rows from file: `tests/data/old_hardware.csv`
* update documentation to make clear the expected behavior regarding start_date

### CODE REVIEW

**Review by visch — CHANGES_REQUESTED** [review]

**Comment by visch** [comment]
There is another way I was thinking about that would allow us to do this, and not have to have a configuration option. We could store the last modified date, and a hash of the file(s) at that last modified date. If the hash is the same as what's in the state don't sync the files, if it isn't the same sync the files.

**Comment by rvantunes** [comment]
@visch I'm not sure if the hash would work, because if the hash changes between the execution, the last modified for the file will change as well, in this case, we don't need the hash, because it will be processed in the next execution since the last modified changed.

my concern is with the happy path where the data pipeline runs every day with success.
In this case, the last processed file will always be synced again by the next execution, which means every execution is going to duplicate data from the last processed file from the previous execution, even if there was no error.

The only thing that makes sense in ‘greater than or equal’ logic is when there is an error during the pipeline execution, this way the next execution will retry the sync for the failed file, is it the case?

Assuming this is the case, we could add the `_sdc_line_number` in the state which means the last line processed with success saved on the state.
In the happy path, this would be the last row of the file. In the next execution,
* If the `_sdc_line_number` == the number of rows in the file then skip the file.
* otherwise skip the number of rows from `_sdc_line_number`. 

this solution would not prevent data from being duplicated in case of errors (which is ok by design), since the state is not saved on each processed row, but minimizes the number of duplicated rows and could keep the ‘greater than or equal’ logic.

Does it make sense for you? Do you think it is feasible?

**Comment by visch** [comment]
> @visch I'm not sure if the hash would work, because if the hash changes between the execution, the last modified for the file will change as well, in this case, we don't need the hash, because it will be processed in the next execution since the last modified changed.

My point is that another file could be added to the file system with that last modified date. Hopefully all file systems wouldn't allow the file to be updated and the last modified date to be changed I agree (we'd have other issues and incremental just wouldn't work for that scenario)





> my concern is with the happy path where the data pipeline runs every day with success. In this case, the last processed file will always be synced again by the next execution, which means every execution is going to duplicate data from the last processed file from the previous execution, even if there was no error.
> 




> The only thing that makes sense in ‘greater than or equal’ logic is when there is an error during the pipeline execution, this way the next execution will retry the sync for the failed file, is it the case?
> 
Part of it, have you read that link I posted?

> Assuming this is the case, we could add the `_sdc_line_number` in the state which means the last line processed with success saved on the state. In the happy path, this would be the last row of the file. In the next execution,
> 
> * If the `_sdc_line_number` == the number of rows in the file then skip the file.
> * otherwise skip the number of rows from `_sdc_line_number`.
> 
> this solution would not prevent data from being duplicated in case of errors (which is ok by design), since the state is not saved on each processed row, but minimizes the number of duplicated rows and could keep the ‘greater than or equal’ logic.
> 
> Does it make sense for you? Do you think it is feasible?

The line number isn't the main concern, and that's already handled today anyway so we should be good there

**Comment by rvantunes** [comment]
>Part of it, have you read that link I posted?
yes, and this document is not clear about the reasons behind the decision of ‘greater than or equal’ logic.

**Comment by rvantunes** [comment]
closing the pr since it is by design duplicate data:

>"It does also mean that the last record streamed in one execution is likely to be the first record streamed in a subsequent execution."

https://sdk.meltano.com/en/latest/implementation/at_least_once.html#cause-1-greater-than-or-equal-to-comparisons

**Comment by visch** [comment]
>> Part of it, have you read that link I posted?
 
> yes, and this document is not clear about the reasons behind the decision of ‘greater than or equal’ logic.

@rvantunes , kind of True but it's also possible to make this happen with the hash we talked about. If it's not a big deal to get extra data then this works too!

**Pull request closed without merging**
